runziggurat/algorand

- README.md
- tools/logging.config
- tools/setup_env.sh
- tools/ziggurat_network_template.json
- Nodes shouldn't try to access anything outside of their temp folders, so copy the logging.config to private network directories
- Small readme update
- Index private network nodes and wallets to start from zero
> chore: disable telemetry in our private network

- Cargo.toml
- src/setup/config.rs
- src/setup/constants.rs
- src/setup/mod.rs
- src/setup/node.rs
- Added NodeBuilder implementation:
- Reads NodeMetaData from "~/.ziggurat/algorand/setup/config.toml".
- Can spawn one node (at the moment) using the preconfigured node stored at "~/.ziggurat/algorand/private_network/Node0".
- Can configure logging.
- Added Node implementation:
- Can be stopped (killed).
- Tests:
- A simple 'start/stop' node test is included. Will be deprecated later.
> feat: add node implementation

- src/setup/config.rs
- src/setup/constants.rs
- src/setup/node.rs
The node uses two addresses which are automatically selected once the node is started. Both addresses are located in files in the node's directory:
- The REST API address is located in the `algod.net` file.
- The network address is located in the `algod-listen.net` file.
These files are the only way to fetch these addresses.
> feat: fetch the node's addresses

- tools/setup_env.sh
- The default log level is 4 (info). Override that value with log level 5 (verbose / debug) in the node's configuration JSON file.
>  chore: increase the log lvl in the config file

- src/setup/config.rs
- src/setup/constants.rs
- src/setup/node.rs
- The node's network address should be listening for incoming connections if the node has started properly.
- Variable correctly renamed in `config.rs`
> feat: verify the node is running after startup

- SPEC.md
- The initial version contains general Ziggurat info.
- Documentation for the first two conformance tests.
> doc: Add a draft version of the SPEC document

- Cargo.toml
- SPEC.md
- src/protocol/constants.rs
- src/protocol/handshake.rs
- src/protocol/mod.rs
- src/tests/conformance/mod.rs
- src/tests/conformance/post_handshake/mod.rs
- src/tests/conformance/post_handshake/query/get_block.rs
- src/tests/conformance/post_handshake/query/mod.rs
- src/tools/mod.rs
- src/tools/rpc.rs
- C003 test: Performs a handshake and then it fetches a block from the node using the V1 algod API (the same way the node asks for blocks after it initiates a handshake towards the synth node).
- Implemented RPC call to fetch blocks.
- SPEC.md updated.
> feat: c003 get block

- src/setup/config.rs
- src/setup/node.rs
- src/tests/conformance/handshake.rs
- src/tests/conformance/post_handshake/query/get_block.rs
- src/tools/rpc.rs
~Two commits:~
EDIT:
Three commits:
```git
chore: optimize c003 test
- include extra comments for the rpc.rs file
```
```
chore: avoid using unwrap
- rather expect everything :^)
```
```
chore: align crash message styles
- expect/panic/assert messages should all be lower-case messages
```
> chore: optimize c003 test and use `expect`

- SPEC.md
- src/tests/conformance/handshake.rs
- src/tests/conformance/post_handshake/query/get_block.rs
- src/tools/constants.rs
- src/tools/synthetic_node.rs
- new `c003` test: expect to receive no messages if the handshake procedure is skipped after the connection is established.
- renamed the old `c003` (`get_blocks`) test to `c004` since the new test is a handshake-related test similar to the `c001` and `c002` tests.
> feat: c003 test - expect no msgs before the handshake

- tools/setup_env.sh
The project name is generic, so I renamed my local directory `ziggurat-algorand`. This updates the setup script to support a renamed project directory.
> Check for root directory rename in setup script.

- SPEC.md
- src/protocol/codecs/algomsg.rs
- src/protocol/codecs/mod.rs
- src/protocol/codecs/msgpack.rs
- src/protocol/codecs/payload.rs
- src/tests/conformance/post_handshake/broadcast/mod.rs
- src/tests/conformance/post_handshake/broadcast/proposalpayload.rs
- src/tests/conformance/post_handshake/mod.rs
- src/tools/rpc.rs
This PR consists of two commits:
```
feat: add ProposePayload message deserializer 
- also: move small parts of rpc.rs code to msgpack.rs
```
```
feat: c007 - expect ProposalPayload message 
```
Extra info:
ProposePayload is not fully deserialized, there is a to-do for that.
The parts that are not serialized are 64-byte fields, which are not easy to deserialize. But that's still not crucial for the first test for this message.
> Add C007: expect proposal payload message

- README.md
- SPEC.md
- src/protocol/codecs/algomsg.rs
- src/protocol/codecs/mod.rs
- src/protocol/codecs/payload.rs
- src/protocol/codecs/tagmsg.rs
- src/protocol/writing.rs
- src/tests/conformance/post_handshake/msg_of_interest.rs
- src/tools/synthetic_node.rs
Includes three commits:
```
feat: algomsg/tagmsg/payload codecs - impl Encoder 
```
```
feat: add unicast send for synthetic_node 
- also include recv_message_timeout function
``` 
```
feat: add c005_t2 test - send a MessageOfInterest 
```
> Add C005_t2 test: send a MsgOfInterest back to the node

- src/tests/conformance/post_handshake/query/ping.rs
- a test which waits for any non-broadcast message within the first ten minutes after the handshake.
> feat: add a test-check for a keep-alive service

- README.md
- SPEC.md
- src/protocol/codecs/msgpack.rs
- src/protocol/codecs/payload.rs
- src/protocol/codecs/tagmsg.rs
- src/protocol/codecs/topic.rs
- src/tests/conformance/post_handshake/query/get_block.rs
Commits:
```git
feat: add new msgs for the topic codec
- Add UniEnsBlockReq message.
- Add TopicMsgResp message with sub-messages:
- UniEnsBlockRsp
- ErrorRsp
- Topic unmarshalling now supports also reading u16 integers (prev only u8).
```
```git
feat: add test for UniEnsBlockReq/TopicMsgResp msgs
Included test in SPEC.md as a C010 test.
```
> feat: add test for UniEnsBlockReq/TopicMsgResp msgs

- src/tests/conformance/post_handshake/query/get_block.rs
- tools/setup_env.sh
Two commits:
```
chore: increase setup_env.sh max_conn_limit_per_ip 
Increasing the limit will make performance testing easier.
```
```
chore: setup_env.sh - run the private network for 20 secs
- Running the private network for 20 seconds will ensure that at
least four rounds are created in that time (which is needed
for certain tests).
- update c004 test to use the first four rounds
```
> Setup script update - increase max_conn_limit_per_ip, generate at least 4 rounds in the PN

- README.md
- src/protocol/codecs/topic.rs
- src/tests/conformance/post_handshake/query/get_block.rs
- original test which expects both block and request is renamed to t1
- t2 added: expects block only in the request
- t3 added: expects cert only in the request
> feat: UNI_ENS_BLOCK_REQ tests for all req-types

- SPEC.md
- src/protocol/codecs/payload.rs
- src/protocol/codecs/tagmsg.rs
- src/protocol/codecs/topic.rs
- src/tests/conformance/post_handshake/query/get_block.rs
```
feat: add codec support for UniCatchupReq msg
```
```
feat: get_block c010 subtests for UniCatchupReq msg
- All tests are based on existing t1-t4 for UniEnsBlockReq message
which has the same structure.
- SPEC doc updated accordingly.
```
> feat: test for the UniCatchupReq msg 

- Cargo.toml
- src/tests/conformance/handshake.rs
- src/tests/conformance/post_handshake/net_prio_response.rs
- src/tools/synthetic_node.rs
- added required support for a `start_listening()` method for the `SyntheticNode`
- tests updated according to this change
> deps: uplift pea2pea to 0.43

- src/setup/node.rs
- tools/setup_env.sh
Commands should begin with ./ to be properly executed under Linux.
To do so, setup_env script need to be fixed.
> chore: change way of starting algod process

- Cargo.toml
- src/protocol/codecs/msgpack.rs
- use algod addresses with a checksum that are encoded in base64 format
- update existing addresses to use `Address` instead of `HashDigest`
Some of the code has been copied from [here](https://github.com/manuelmauro/algonaut/tree/main/algonaut_core/src/lib.rs). Algonaut is an excellent tool!
> feat: introduce proper algod addresses

- Cargo.toml
- src/protocol/codecs/msgpack.rs
- src/protocol/codecs/payload.rs
- src/protocol/codecs/tagmsg.rs
- src/tools/rpc.rs
- adds support for deserializing Transaction messages from the node.
- extra: removed todo - now all fields in the agreementVote and the proposalPayload messages are deserialized.
Some of the code has been copied/modified from [here](https://github.com/manuelmauro/algonaut/tree/main/algonaut_core/src/lib.rs). Algonaut is an excellent tool!
> feat: support for msgpack deserializing txn msgs

- src/setup/config.rs
- src/setup/constants.rs
- src/setup/kmd/config.rs
- src/setup/kmd/constants.rs
- src/setup/kmd/mod.rs
- src/setup/mod.rs
- src/setup/node.rs
- src/tests/conformance/post_handshake/cmd/mod.rs
- src/tests/conformance/post_handshake/cmd/transaction.rs
- src/tests/conformance/post_handshake/mod.rs
The solution for the `kmd` is based on setup/node solution, so there's not much new original content here.
The initial test provided here in `transaction.rs` contains a full plan for that test
commits:
```
feat: add initial version of transaction test
- current test just starts the node and the kmd instance
- includes a TODO list with the plan for the test (coming soon)
```
```
feat: introduce start/stop support for kmd
The Key Management Daemon (kmd) is a low level wallet and key management
tool. It works in conjunction with algod and goal to keep secrets safe.
```
```
chore: rename node's setup const
```
> introduce start/stop support for kmd

- src/setup/kmd/mod.rs
- src/setup/kmd/rest_api/client.rs
- src/setup/kmd/rest_api/message.rs
- src/tests/conformance/post_handshake/cmd/transaction.rs
Unlock the wallet and return a wallet handle token that can be used for subsequent operations. These tokens expire periodically and must be renewed. You can POST the token to /v1/wallet/info to see how much time remains until expiration, and renew it with /v1/wallet/renew. When you're done, you can invalidate the token with /v1/wallet/release.
> feat(kmd): add REST API support for /v1/wallet/init

- src/protocol/codecs/msgpack.rs
- src/tests/conformance/post_handshake/cmd/mod.rs
- src/tests/conformance/post_handshake/cmd/transaction.rs
Some refactor work needed for msg_digest_skip test
Also in another commit:
- `impl From<&Vec<u8>> for HashDigest`
> refactor: break out common code from txn test

- README.md
- SPEC.md
- src/tests/performance/mod.rs
- src/tests/performance/prio_test.rs
- src/tools/constants.rs
This test checks if the node behaves as expected under load when some peers are sending higher priority messages and some other peer is trying to request blocks with certificates (that are lower priority messages).
Test will be refactored in the next PR - message hardcodes will be changed to message factory that will construct messages and payloads to be used during tests.
> feat: higher/lower priority messages load test

- README.md
- SPEC.md
- src/protocol/codecs/algomsg.rs
- src/protocol/reading.rs
- src/tests/conformance/mod.rs
- src/tests/conformance/post_handshake/cmd/mod.rs
- src/tests/conformance/post_handshake/mod.rs
- src/tests/conformance/post_handshake/query/ping.rs
- src/tests/performance/get_blocks.rs
- src/tests/performance/prio_test.rs
- src/tests/resistance/mod.rs
- src/tests/resistance/post_handshake/enormous_message.rs
- src/tests/resistance/post_handshake/mod.rs
- src/tools/constants.rs
- src/tools/inner_node.rs
- src/tools/synthetic_node.rs
```
feat: resistance test - send an enormous message
r004_t1 test sends an enormous valid message and expects to stay
connected with the node.
```
```
refactor: send also raw msg to the synth node
In certain cases synthetic_node will need to use raw data as well, besides the parsed payload.
```
> feat: resistance test - send an enormous message

- README.md
- SPEC.md
- src/tests/conformance/post_handshake/cmd/mod.rs
- src/tests/conformance/post_handshake/cmd/msg_digest_skip.rs
- src/tests/resistance/mod.rs
- src/tests/resistance/post_handshake/enormous_message.rs
- src/tests/resistance/post_handshake/mod.rs
Send a huge valid proposal payload message to the node from one synthetic node and expect to recieve a MsgDigestSkip message on the other synthetic node.
> feat: add MsgDigestSkip test

- SPEC.md
- src/protocol/mod.rs
- src/protocol/payload_factory.rs
- src/tests/performance/prio_test.rs
Two types of peers can be defined now: normal peers which generate and receive some traffic that is measured and high traffic peers which try to flood the node with some other traffic.
Some of the conecpts need to be extended - factory should contain also first message generation (as well as custom message with some custom values) and each payload type should contain matcher associated with it.
> refactor: prio tests changed to be generic traffic tests

- src/tests/conformance/handshake.rs
- src/tests/conformance/post_handshake/query/ping.rs
- src/tests/performance/get_blocks.rs
- src/tests/performance/prio_test.rs
- src/tests/resistance/handshake.rs
- src/tools/metrics/recorder.rs
The only actual diff in [tests/performance/get_blocks.rs](https://github.com/runziggurat/algorand/pull/70/files#diff-78b65b6769d31e70406b04b3d4d9def2f35c4792a8aff98201c1bab7c707e9c1) is:
```
#[cfg_attr(
not(feature = "performance"),
ignore = "run this test with the 'performance' feature enabled"
)]
```
Why is git doing this... 🤔
> chore: update description for ignored tests

- README.md
- src/tests/resistance/handshake.rs
Also in a separate `doc` commit:
- removed the "WIP" tag from the Readme.md.
> Uncomment failing tests

- README.md
This PR addresses the Improvement Bucket Task: `Add deps.rs badges to all our readme documents`
> chore: add deps.rs badge to readme
