runziggurat/algorand

Cargo.toml
src/lib.rs
src/protocol/codecs/mod.rs
src/protocol/codecs/websocketcodec.rs
src/protocol/handshake.rs
src/protocol/mod.rs
src/protocol/reading.rs
src/protocol/writing.rs
src/tests/conformance/handshake.rs
src/tests/conformance/mod.rs
src/tests/mod.rs
src/tools/inner_node.rs
src/tools/mod.rs
src/tools/synthetic_node.rs

- Added a handshake test where the synthetic node initiates a connection towards the node. The test expects the handshake procedure to succeed.
- Added basic Synthetic node impl
- WebSocket codec impl
- Synthetic node tracing impl
- Implemented pea2pea handshake trait procedure for the initiator side.

feat: Add conformance test c001

---

src/protocol/handshake.rs

- Use different (random) WebSocket keys across the tests
- Moved certain WebSocket handshake data to const format

chore: use random sec-websocket key

---

src/protocol/handshake.rs
src/setup/config.rs
src/setup/node.rs
src/tests/conformance/handshake.rs
src/tools/constants.rs
src/tools/mod.rs
src/tools/synthetic_node.rs

- The node correctly performs a handshake from the initiator side.

feat: add c002 handshake test

---

SPEC.md
src/protocol/codecs/algomsg.rs
src/protocol/codecs/mod.rs
src/protocol/codecs/payload.rs
src/protocol/codecs/tagmsg.rs
src/protocol/codecs/topic.rs
src/protocol/mod.rs
src/protocol/reading.rs
src/tests/conformance/handshake.rs
src/tests/conformance/post_handshake/mod.rs
src/tests/conformance/post_handshake/msg_of_interest.rs
src/tools/inner_node.rs
src/tools/synthetic_node.rs

- includes c005 pt1 test.
- implements algomsgcodec.
- includes all message tags.
- implements topic codec.
- SPEC updated accordingly.

feat: add c005 - expect message of interest

---

SPEC.md

- change test index to table format
- add network protocol test coverage in the spec doc

SPEC update: index table and protocol test coverage table

---

SPEC.md
src/protocol/codecs/msgpack.rs
src/protocol/codecs/payload.rs
src/tests/conformance/post_handshake/broadcast/agreementvote.rs
src/tests/conformance/post_handshake/broadcast/mod.rs

feat: c008 - expect AgreementVote message

---

src/protocol/codecs/tagmsg.rs
src/protocol/codecs/topic.rs

- function renaming in topic.rs
- add Display trait for the Tag struct

feat: add topic encoder

---

SPEC.md
src/protocol/codecs/algomsg.rs
src/protocol/codecs/payload.rs
src/protocol/codecs/topic.rs
src/tests/conformance/post_handshake/msg_of_interest.rs

- expect to receive no messages after sending an empty tag list within the MsgOfInterest message
- SPEC updated accordingly
- a few typos fixed

feat: c006 test - send empty tag list in MsgOfInterest

---

SPEC.md

Update the test table index with the latest report.

doc: SPEC update

---

src/tests/conformance/post_handshake/query/get_block.rs

- New subtest added t4: expect that the node will deny request with a reject response.

feat: UniEnsBlockReq get non-existent block

---

README.md
src/protocol/handshake.rs

- doc: uplift algod version
- chore: use genesis const in the handshake procedure

Uplift algorand version

---

src/protocol/codecs/payload.rs
src/protocol/codecs/tagmsg.rs

- encoding for `AgreementVote` message included within the commit

feat: add codec support for MsgDigestSkip message

---

README.md
src/tools/ips.rs
src/tools/mod.rs
tools/ips.py

Source IP generation code taken from xrpl.

Chore: source IP generation

---

README.md
SPEC.md
src/setup/node/mod.rs
src/tests/mod.rs
src/tests/performance/get_blocks.rs
src/tests/performance/mod.rs
src/tools/synthetic_node.rs

Getting blocks of data using UniEnsBlockReq message.
Results should be inspected manually after test is complete.

feat: get_block performance test

---

README.md
SPEC.md
src/protocol/codecs/msgpack.rs
src/protocol/codecs/payload.rs
src/protocol/codecs/tagmsg.rs
src/setup/kmd/mod.rs
src/setup/kmd/rest_api/client.rs
src/setup/kmd/rest_api/message.rs
src/setup/node/rest_api/client.rs
src/setup/node/rest_api/message.rs
src/tests/conformance/post_handshake/cmd/transaction.rs

commits:
```
feat: add tnx_params support for node rest API
feat(kmd): support - get_keys, sign_transaction
feat: add serialization for MultiSig
feat: synth node support for sending raw bytes
feat: full transaction test implementation
```

feat: full transaction test implementation 

---

src/protocol/handshake.rs
src/protocol/mod.rs
src/tests/conformance/post_handshake/net_prio_response.rs
src/tools/inner_node.rs
src/tools/synthetic_node.rs

- handshake procedure slightly refactored
- netprio test aligned with the new solution

feat: add flexible handshake configuration

---

README.md
SPEC.md
src/setup/node/mod.rs
src/tests/mod.rs
src/tests/resistance/handshake.rs
src/tests/resistance/mod.rs

the second part of the same test will be submitted separately

feat: add handshake resistance test

---

src/protocol/handshake.rs
src/tests/resistance/handshake.rs

feat: update handshake resistance test

---

Cargo.toml
README.md
SPEC.md
src/tests/resistance/handshake.rs
src/tests/resistance/mod.rs
src/tests/resistance/random_bytes.rs
src/tools/mod.rs
src/tools/util.rs

```
feat(test): send random bytes prehandshake
```
```
chore: typo fix in the test name
```
```
feat(util): add random byte generator
- `rand` crate included in the Cargo.toml
- added a function which generates random data
```

feat(test): send random bytes prehandshake 

---

Cargo.toml

- no adaption needed, but let's test the new version ;-)

deps: uplift pea2pea to 0.44

---

Cargo.toml
README.md
src/tests/performance/get_blocks.rs
src/tests/performance/prio_test.rs
tools/ips.py

```
doc: update test instructions
- Allow to run tests with multiple threads
- Separate and update instructions for running preformance tests
```
```
chore: run preformance tests with a specific feature
Performance test require additional configuration,
so run those tests with:
cargo +stable test performance --features performance
``` 
```
chore: ips.py update
- run only the necessary commands within the sudo context
- print commands which the script runs - better output feedback
```

doc updates, ips script updates

---

src/protocol/payload_factory.rs
src/tests/performance/prio_test.rs

Now it's possible to generate message bundles and provide customizers to change payload as one need. Default customizer is provided in the payload factory.

feat: extended payload factory with new generation options 

---

SPEC.md
src/protocol/payload_factory.rs
src/tests/performance/get_blocks.rs
src/tests/performance/prio_test.rs

Block test use now consts and payload factory.
Added new sub-case for traffic tests.

chore: changed perf tests to use consts and added new test sub-case

---

tools/ips.py

- make sure the first sudo command is executed in the foreground so the user could enter the credentials

chore: update ips.py script

---

src/protocol/handshake.rs

- Add a gossip genesis option in the handshake configuration struct

chore: add gossip genesis option

---

Cargo.toml
src/protocol/codecs/msgpack.rs
src/protocol/handshake.rs
src/setup/kmd/mod.rs
src/setup/node/mod.rs
src/tools/synthetic_node.rs

extra:
[chore: resolve nightly clippy warnings](https://github.com/runziggurat/algorand/commit/786f12356a67c460949ad6a06d2e5e480ef622ef)

deps: uplift pea2pea to 0.45 
